name: CI
run-name: Static site deployment
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Zola, and sshpass
        run: |
          sudo snap install zola --edge &
          sudo apt-get install sshpass -y &
          wait
    
      - name: zola check
        run: zola check

      - name: zola build
        run: zola build

      - name: Set up SSH known hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}

      - name: Deploy the website to server
        run: |
          sshpass -p "$DEPLOY_PASSWORD" rsync -avx -e 'ssh -T' --delete --exclude '.ssh' public/ $DEPLOY_USERNAME@$DEPLOY_SERVER:./
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
