name: CI
run-name: Static site deployment
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Zola, Minify, and sshpass
        run: |
          sudo snap install zola --edge &
          sudo apt-get install minify sshpass -y &
          wait
    
      - name: zola check
        run: zola check

      - name: zola build
        run: zola build

      - name: Minify site
        run: minify -r -a -s -v -o ready/ --html-keep-quotes --html-keep-document-tags --js-keep-var-names public/

      - name: Set up SSH known hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}

      - name: Deploy the website to server
        run: |
          sshpass -p "$DEPLOY_PASSWORD" rsync -avx -e 'ssh -T' --delete --exclude '.ssh' ready/ $DEPLOY_USERNAME@$DEPLOY_SERVER:./
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}